name: Build Release Artifacts

on:
  push:
    branches: [ release/* ]

jobs:
  build-exe:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '14'
      - uses: DeLaGuardo/setup-clojure@master
        with:
          lein: latest
      - name: Build 3D Scene
        run: |
             lein uberjar
             jpackage --input target --main-jar backend-3d-scene.jar --name "scene" --main-class backend_3d_scene.core --type exe --win-menu
        working-directory: ./backend-3d-scene
      - name: View artifacts
        run: dir
        working-directory: ./backend-3d-scene
      - uses: actions/upload-artifact@v2
        with:
            name: windows
            path: backend-3d-scene\scene-1.0.exe
